# Generated by Django 2.2.7 on 2020-05-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Improvement_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='idea_duration',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='idea_file',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_close_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_impact',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_improvement',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_status',
            field=models.CharField(blank=True, choices=[('WIP', 'WIP'), ('Implemented', 'Implemented'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Close', 'Close')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Idea_QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.IntegerField(default=0)),
                ('idea_qc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('idea_qc_mail', models.EmailField(default=None, max_length=254)),
                ('idea_qc_date', models.DateTimeField(auto_now_add=True)),
                ('idea_qc_remark', models.TextField(blank=True, default=None, null=True)),
                ('idea_qc_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=200)),
                ('idea_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storm.Idea')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=0)),
                ('commenter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('commenter_mail', models.EmailField(default=None, max_length=254)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=None)),
                ('comment_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storm.Idea')),
            ],
        ),
    ]
