# Generated by Django 2.2.6 on 2020-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('WIP', 'WIP'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
    ]
