# Generated by Django 2.2.7 on 2020-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0003_judgeselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_remark',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=200),
        ),
    ]
