# Generated by Django 2.2.7 on 2020-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0004_auto_20200405_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_creator_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
