# Generated by Django 2.2.7 on 2020-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0006_auto_20200429_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=0)),
                ('commenter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('commenter_mail', models.EmailField(default=None, max_length=254)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Idea_QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.IntegerField(default=0)),
                ('idea_qc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('idea_qc_mail', models.EmailField(default=None, max_length=254)),
                ('idea_qc_date', models.DateTimeField(auto_now_add=True)),
                ('idea_qc_remark', models.TextField(blank=True, default=None, null=True)),
                ('idea_qc_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='idea_creator_team',
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_status',
            field=models.CharField(choices=[('WIP', 'WIP'), ('Implemented', 'Implemented'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Close', 'Close')], default=None, max_length=200),
        ),
    ]
