# Generated by Django 2.2.7 on 2020-04-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0007_auto_20200429_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_remark',
        ),
    ]
