# Generated by Django 2.2.7 on 2020-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0008_remove_idea_idea_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_duration',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_impact',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_improvement',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
