# Generated by Django 2.2.7 on 2020-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0009_auto_20200430_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_status',
            field=models.CharField(blank=True, choices=[('WIP', 'WIP'), ('Implemented', 'Implemented'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Close', 'Close')], default=None, max_length=200, null=True),
        ),
    ]
