# Generated by Django 2.2.7 on 2020-04-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0010_auto_20200430_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_file',
        ),
    ]
