# Generated by Django 2.2.7 on 2020-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0011_remove_idea_idea_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
