# Generated by Django 2.2.7 on 2020-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0012_idea_idea_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_file',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_file_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
