# Generated by Django 2.2.7 on 2020-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0013_auto_20200430_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_close_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
